packages:
  - ./libs/*
  - ./modules/*
  - ./demo/*
overrides:
  '@ungap/structured-clone': ^1.3.1
  encoding-sniffer: ^1.0.2
allowBuilds:
  core-js-pure: true
  esbuild: true
shamefullyHoist: true
minimumReleaseAgeExclude:
  - '@journeyapps/*'
  - '@journeyapps-labs/*'
  - '@journeyapps-platform/*'
  - '@types/node@26.1.0'
  - js-yaml@5.2.1
  - prettier@3.9.5
  - '@projectstorm/*'
  - concurrently@10.0.4
  - minimatch@10.2.6
  - webpack-cli@7.2.2
  - webpack@5.109.1
