# Action to publish packages under the `next` tag for testing
# Packages are versioned as `0.0.0-{tag}-DATETIMESTAMP`
name: Build and test

on:
  pull_request:

jobs:
  libs_and_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-node-pnpm

      - name: Build libs and modules
        run: pnpm build

      - name: Test
        run: pnpm test
