name: Prettier check

# This action works with pull requests and pushes
on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Check out the repository first.

      - uses: ./.github/actions/setup-node-pnpm

      - name: Prettier
        run: pnpm prettier --check --config .prettierrc '**/*.{ts,tsx,js,jsx}'
